# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo "github.ref : ${{github.ref}}"
        echo "github.ref_name : ${{github.ref_name}}"
